global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'messagepulse-core'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['messagepulse-core:8080']
